env:
  - SH=bash
language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.ini
  - pip install codecov
# command to run tests
before_script:
  - mkdir -p testresult
script:
  - locust -f ./example/locust/test_http.py --conf ./example/locust/host.conf
after_script:
  - codecov -t CODECOV_TOKEN
  - bash <(curl -s https://codecov.io/bash)
